### ISSUE TITLE
Can the lib be used with World Space/XR

### ISSUE THREAD

**Issue by ahoys** [ReactUnity/core#21]
I'm developing an XR-project (VR) and I'd like to create the floating main menu with React as I'm very familiar with the library.

However, I'm unable to get ReactUnity work in other than Screen Space render mode. And as this is a VR-project, Screen Space is not usable for me.

1. Does ReactUnity support World Space rendering?
2. Does ReactUnity somehow not support XR?

![image](https://user-images.githubusercontent.com/14974945/130464032-b586ce63-1aeb-41c0-a8e4-4eae236f28d4.png)

There is this buggy white pane rendered that appears to be empty:

![image](https://user-images.githubusercontent.com/14974945/130464258-db6a4a18-83c2-4071-b1de-37f6196ae7bf.png)

**Comment by KurtGokhan** [comment]
Yes, world space rendering is supported. I haven't tested VR/XR yet but it should also be working.

You need to setup GameObject like this:

![image](https://user-images.githubusercontent.com/6034931/130468234-e4aca809-2364-4a20-85ce-f140b3e07c73.png)

This is because ReactUnity takes width directly from the element it is attached to. So you need to set Canvas to a high width/height like `1000` then scale it down with something like `1/1000`. After that you need to add another GameObject under the canvas and attach `ReactUnityUGUI` component to that.

**Comment by ahoys** [comment]
Ok, I got it otherwise working but for some reason the react content is only rendered for the left eye. I'm using a single pass instanced render mode (URP). Does ReactUnity perhaps use some shader that isn't single pass compatible?

**Comment by KurtGokhan** [comment]
I am not sure. I will check it asap. I guess the custom shared I wrote isn't compatible.

**Comment by ahoys** [comment]
Ok I found a small workaround. Adding a separate black RawImage to act as a background seems to work to some degree.
Text seems to render just fine for both eyes.

So there's something going on with the "backgroundColor" style-attribute.

**Comment by KurtGokhan** [comment]
Seems like the culprit is Unity's `Mask`. Apparently, `Mask` does not work in stereo rendering. I write a custom mask shader and component to solve this issue.

Setting `background-color` also creates a mask so that explains it. Other properties like `overflow`, `border` and `box-shadow` will also have this issue.

**Comment by KurtGokhan** [comment]
Fixed in 0.4.2. Deploying right now.

**Comment by KurtGokhan** [comment]
Fixed in 0.4.3. Let me know if you have other issues.

**Comment by ahoys** [comment]
That was fast, thank you! The one-eye rendering bug seems to be solved now. However, I stumbled upon a few new ones now:

(The following are from 0.4.3)

(1)
This may be a bit (really) hard to see, but the screen (background) has a strange banding effect going on. Like some lines that seem to be mirroring the HMD rotation. Difficult to see in the pic, but quite noticeable in VR, especially as they're constantly rotating.

(2) Another thing are the white borders. Didn't have those with the RawImage approach.
![image](https://user-images.githubusercontent.com/14974945/130500189-85fa2b66-2b5b-4bfb-846c-4340955b0d64.png)

And one more is that the base "page" beneath the app seems to stay white, even though the root component (App) is set to be `background: black` in css. This causes two issues: 1) as the screen appears, the UI is initially white and then rapidly switches to black. 2) As in the picture below, any opacity to the canvas group is displayed as white, instead of as the actual background color. This is unfortunate if the UI canvas is animated to appear/disappear like in this case.
![image](https://user-images.githubusercontent.com/14974945/130500491-de507e2f-faf7-4cb7-81c1-20721737901a.png)
```
import './app.css';

const App = () => <view id={'app'}>Home</view>;

Renderer.render(<App />);
```
```
#app {
  position: absolute;
  top: 48px;
  right: 48px;
  bottom: 48px;
  left: 48px;
  overflow: hidden;
  color: #ffffff;
  background: #000000;
}
```
And here's a vid just to be safe:
[https://youtu.be/Chblb7nqGQk](https://youtu.be/Chblb7nqGQk)

**Comment by KurtGokhan** [comment]
About 2:

There is a root element above the `#app` element. It is the GameObject which you assign `ReactUnityUGUI`. I guess white color comes from that. You should remove image components from that element if they exist. You can then style root element like:

```
:root {
  background: #000000;
}
```

> any opacity to the canvas group is displayed as white

I don't understand this part. Can you try the solution above and see if that fixes it?


I will check why the border appears. I guess there are some floating point errors.

**Comment by ahoys** [comment]
The :root didn't solve the mystery, but it did perhaps reveal a clue; the black "border" caused by the root's black background doesn't seem to have the same fade to white issue as the background inside the App. As the menu fades away, the root background fades properly but the App container switches to white.
```
:root {
  background-color: #000000;
}
```

![image](https://user-images.githubusercontent.com/14974945/130507780-c91c17f3-9167-42e3-b7db-d833ac16872f.png)

> I don't understand this part. Can you try the solution above and see if that fixes it?

I'm altering the alpha of the parent canvas to programmatically fade-in/out the menu as [seen in the video](https://youtu.be/Chblb7nqGQk). This should fade out the menu on close, but the issue is that the App component turns white if the parent canvas has alpha applied that != 1.0.

![image](https://user-images.githubusercontent.com/14974945/130508344-5fbd1258-23b8-42e7-bc9f-0dafa6ec96ed.png)

**Comment by ahoys** [comment]
And here's a pic of the strange line artifacts with some Photoshop enhancement:
![image](https://user-images.githubusercontent.com/14974945/130509626-127de5d3-3f53-4ba5-bad7-88206a9c292d.png)

These lines rotate and move (probably because the canvas is locked to HMD orientation and the lines seem like some kind of reflection perhaps?).

**Comment by KurtGokhan** [comment]
I found the white background. Seems like I introduced this bug in the last version. It was a bit rushed. Should be fixed now but I don't know if it is the source of your issue.

About the diagonal lines, I don't think they are caused by reflection. The UI shaders are unlit. In any case, I explicitly disabled reflection and specular. Issue may be fixed in 0.4.4.

To me, it seems like sun flare is clipping through UI. Can you try with a regular Unity Canvas and see if the same problem happens?

**Comment by ahoys** [comment]
The 0.4.4 fixed all the issues stated above, even the lines! Bravo 👏🏻

**Comment by KurtGokhan** [comment]
Thank you for your help. Testing ReactUnity in all platforms can be hard for me alone so I appreciate when users report bugs. Sorry for the trouble.
